language: python
services:
- docker
python:
- '3.6'
install:
- pip install -r requirements.dev.txt
- pip install --upgrade .
script:
- tox
notifications:
  email: false
deploy:
- provider: pypi
  user: ChrisTimperley
  password:
    secure: Dzn1oR+NHtpx6Us0auFNP5RB6JRheehUZgyxM7DQRAv52ilpFzug39ror3NUDG/LKoCl76BGnmTjwx8oN0aUa34IzMO0mX/tgjMbTDtx6vt8sDJtUKpGImeleA4euLj15zeYWE6ovIyB3N3sIZgm0f3n0rXyD7Z1rnlx/FEs+IlYD4TDFirxDLmwh37o3aWIQOSMdhI6VjQXWa3Yr5iWFVmktTfe08InvOONwgLVErPhkuWUHbXCSDpSXXmoD00C1Wv5uLwNybpmrI0Wxa5hVGh8xk+IVAMqz6uJu5p+HlZQdomrYBZ67bKDcrygSVg2N3z8LEVxjsYmHF3baEf2RFXHEanM9Fo+O12rgTi0m1Io3A5KPCuPLe+yg7mkBFYKSjXr0wfMUtVN8nSsqw7kY9qA0t6NQHTTjhvoSavaNberaUSs7IfeUMxvP93iU6Sw1ZOAZc07y9h7l8h7NajIZvXRU4kcZJ0d9qwDRBsDn1aZw0w6YtMzU8iDZsbK2OIOCxnhhV6cTjYBd2AEB/T1PPIBq7PLuboS+5KRfv1i48CXpKACjQzWJ0Re4qaTxHxuWNJ5El7q1eJRCcD0VLT7Nr4sSUdX2EH/CPr0qmQPIFyaGBtfv6Hm+8m8Be7+d7T10h2zqMo15xflQAJDnYRP0Plz8Z9bNqSMUoyP0/7Kjjc=
  on:
    tags: true
    python: '3.6'
