language: python
services:
- docker
python:
- '3.6'
install:
- pip install -r requirements.dev.txt
- pip install --upgrade .
script:
- tox
notifications:
  email: false
deploy:
- provider: pypi
  user: ChrisTimperley
  password:
    secure: PvcyJN/S142Q31DW+6VH7IC9DBip1vljrUiH4FCpmYhL1wvGL3j1o0HLeStsn6q1Cxi9x3mDSb0ttMHNsp1NB0DaMGFMTXpBm3/K72lBa9aGv5cOtKxy4w9fP/fQW4/pDc0Q3ePZZSnzKKs5M5c9wYT2SmeIgiamwH5TVg42/pILJZaDyze7ybpoH0ONd0rjgj9YAIJEmOdAuKz+nWhgJBrmFiY2N8xjTp25yMmSAczM/PALUrX3fw1h1Kb0KFd9kZE44On86CH3+vcI7reGAVkDpD1oxwdj59ZWLc1tLxLXS2bIcZJKRFUvlY+sW81lv7bBoTnEp4V4BoR/QbWweV/LvvImcLAbccIxNlgl4YAAz2I12M2oafpcrMIZntQQkQJl6XkInU5FpAuwtaQw3OyAozWxN+YXX9pudG9XnbAjJSAADs+nCe6rMnc33tP0LsyQZCxUfmzt5uB8M2PVL/3O23n4P9NKFTTVl6w2+6HM5QAJp7ZT/T/PoPEjExamfcg//bVGzVeqvdrqFS0aFxrW3IgFpHoTZstwMQTYmsIAV2HU4Zcd6jjXhXdt/1zJz+jd6sPkPbStKcNn+/8oB10whnoKdhmlYzcTq3yQiO8s5QMMMv61MUABA4t50YcRaVsS+eW1LRloGKDBHgcWg0M++ce6tAUt9Vkq1MZnUHI=
  on:
    tags: true
    python: '3.6'
